version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      # The following code is necessary to avoid PyYAML installation errors.
      # See https://github.com/yaml/pyyaml/issues/724#issuecomment-1638636728
      - python -m pip install --upgrade --no-cache-dir --no-build-isolation pyyaml==6.0

sphinx:
  configuration: docs/conf.py

formats: all

python:
  install:
    - requirements: docs/requirements.txt
